### ISSUE TITLE
Error when leaving neovim in background for grace period

### ISSUE THREAD

**Issue by tannerellen** [Zeioth/garbage-day.nvim#1]
If I leave a file open with neovim in the background for the grace period length then come back to neovim there is an error...

Error executing vim.schedule lua callback: ...are/nvim/lazy/garbage-day.nvim/lua/garbage-day/utils.lua:21: attempt to call field 'get_clients' (a nil value)  

<img width="1428" alt="Screenshot 2023-11-05 at 8 07 47 PM" src="https://github.com/Zeioth/garbage-day.nvim/assets/930897/285ba387-05ae-4c7c-96b1-4fca6e2a3a08">

This is in a javascript file attached is my :LspInfo

<img width="979" alt="Screenshot 2023-11-05 at 8 33 23 PM" src="https://github.com/Zeioth/garbage-day.nvim/assets/930897/2634bd4e-5781-4c2e-8057-217dfe3dca00">

**Comment by Zeioth** [comment]
@tannerellen what nvim version are you using? We only support nvim 0.9 and 0.10 (it's in the readme).

In nvim 0.8 of lower, nvim uses `get_active_clients()` instead of `get_clients()`, which causes that error. If this is your case, you can use [lsp-timeout](mhttps://github.com/hinell/lsp-timeout.nvim) which is quite similar.

**Comment by Numkil** [comment]
@Zeioth I have the same error with the grace period. I'm on nvim 0.9.4 on macos. 

![Screenshot 2023-11-06 at 16 50 41](https://github.com/Zeioth/garbage-day.nvim/assets/5604686/a93589af-c9a9-4c5d-b949-a81a2e9ff26e)

**Comment by tannerellen** [comment]
@Zeioth Sorry I meant to say I am using nvim v0.9.4 on Ubuntu.

<img width="735" alt="Screenshot 2023-11-06 at 9 18 23 AM" src="https://github.com/Zeioth/garbage-day.nvim/assets/930897/0074575f-025d-45f2-83f2-b505331cd07d">

**Comment by Zeioth** [comment]
Ok it seems neovim start saying something is deprecated as soon as they push the changes to git (v0.10). That means you need nvim v0.10

I'm gonna check if adding support for v0.9 can be done without adding too much complexity.

**Comment by Zeioth** [comment]
@tannerellen @Numkil I've pushed the fix, you should be able to use it on `nvim 0.9` now.

**Comment by Numkil** [comment]
Yes that works wonderfully! thanks!

**Comment by tannerellen** [comment]
That did the trick. Thanks!
