### ISSUE TITLE
[Bug]  attempt to call field 'get_clients' (a nil value) (nvim 0.9.5)

### ISSUE THREAD

**Issue by andrewcrook** [Zeioth/garbage-day.nvim#12]
Hi @Zeioth  I have started to get an error when it tries to stop a LSP 
I only have fennel-language-server set up and worked fine until a recent update.

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

```
Error executing vim.schedule lua callback: ...are/nvim/lazy/garbage-day.nvim/lua/garbage-day/utils.lua:11: attempt to call field 'get_clients' (a nil value)
stack traceback:
        ...are/nvim/lazy/garbage-day.nvim/lua/garbage-day/utils.lua:11: in function 'stop_lsp'
        ...hare/nvim/lazy/garbage-day.nvim/lua/garbage-day/init.lua:52: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

![Screenshot 2024-05-23 at 22 32 35](https://github.com/Zeioth/garbage-day.nvim/assets/803618/5c80802a-dcc7-4dc2-b23b-5efcb8f55c74)

I believe it is to do with this change?
https://github.com/Zeioth/garbage-day.nvim/commit/c9fb8746479e7c7a0231e7c2a76a1efc19b4b887

The following works fine 
`:lua =vim.lsp.get_active_clients()`

However, the following doesn’t 

`:lua =vim.lsp.get_clients()`

![Screenshot 2024-05-23 at 22 41 05](https://github.com/Zeioth/garbage-day.nvim/assets/803618/a7ede49c-b384-42ec-8151-ae8204df7caf)

I suppose this is an API change for Nvim 0.10 and just needs an if >= 0.10 statement between the nvim API versions.

**Comment by Zeioth** [comment]
Thank you for reporting @andrewcrook 

You can lock your garbage-day version to  `v1.2.0` if you are still on  `nvim 0.9`. Next versions are gonna require the latest stable version (nvim 0.10) or the development vesion (nvim 0.11).

**Comment by andrewcrook** [comment]
@Zeioth  Thanks will lock the version.
I want to give it a couple of weeks before moving to 0.10 for other plugins that may need to catchup..

**Comment by Zeioth** [comment]
Updatig to 0.10 is safe, but for 0.11 some plugins are still catching up because the version was just published for the first time a few days ago.
