### ISSUE TITLE
Don't shutdown LSP client for some cases?

### ISSUE THREAD

**Issue by linrongbin16** [Zeioth/garbage-day.nvim#13]
Hi, when using this plugin, it works great for most of the times.

But recently I found it's not very convenient in some cases:

I am editing/refactoring my project, and I need to switch to browser and check some documents or API references, or even I need to have a 1 hour meeting that totally stops my project. But anyway, after several minutes or even hours pausing, I go back to Neovim editor and try to start editing/refactoring again. I found the LSP clients are already been shutdown.

I think it's appropriate if this plugin don't shutdown those LSP clients that are been used by the _**current buffer**_? A customizable option is better.

**Comment by Zeioth** [comment]
The thing is precisely you might be doing something entirely else (gaming, browsing), and you only want the servers to resume while you are actually using them, regardless if it's the current buffer or not. For now the solution is to just use the option `excluded_lsp_clients`, or set a higher `grace_period`. 

If your CPU is not very powerful, but you have plently of RAM, you might not even want to stop the LSP servers at all.

It would be easy to add an option for this, but IDK if the case of use is strong enough, let me wrap my head around it for a few days.

**Comment by Zeioth** [comment]
@linrongbin16 this is actually the behavior of `aggressive_mode = true` already, as it ignores `grace_period`. It's currently not possible with `aggressive_mode = false`.

The problem of adding something like `never_stop_current_ft = true` is that it doesn't translate very well when `aggressive_move = true` and `never_stop_current_ft = false`.

So while it would be a cool addition, I fear it would add confusion. Please fork the repo if you need the feature. Closing for now, but I'm still open to discuss it.
