### ISSUE TITLE
[request] manually tell garbage-day when to start/stop (or pass it user autocmd events to respond to?)

### ISSUE THREAD

**Issue by megalithic** [Zeioth/garbage-day.nvim#3]
Presently, when in a `GitConflicted` mode, I like to turn off diagnostics and turn off all attached LSP clients. Some of my lsps do weird things when the buffer has git conflict markers, etc. I use `git-conflict.nvim` presently to resolve conflicts and in their hooks, i do the manual start/stop of lsps. 

Is it possible to either, a.) call manual start/stop functions for garbage-day, or; b.) pass in custom autocmd User events that tell tell garbage-day when to start/stop clients (similar to the existing FocusLost/FocusGained default events)?

Thanks!

**Comment by Zeioth** [comment]
If you are starting/stopping lsp servers on the git-conflict.nvim hook and you don't want garbage-day to interfere with that, you could use the option `excluded_lsp_clients` to ignore certain clients.

Also even though this is not documented, you can indeed manually trigger the garbage collection functions the next way:

```lua
local utils = require("garbage-day.utils")
local stopped_lsp_clients = utils.stop_lsp()
local start_lsp_clients = utils.start_lsp(stopped_clients)
```

If one of those solutions cover your case of use, I suggest you to fork the plugin. I've made the code extremely simple and readable on purpose, in case someone needs to do it.
