### ISSUE TITLE
Still detecting `null-ls`?

### ISSUE THREAD

**Issue by neuromaancer** [Zeioth/garbage-day.nvim#4]
I am using `LazyVim` as my Neovim distro, so I didn't use `null-ls` at all. I use the configuration below: 
```lua
return {
    "zeioth/garbage-day.nvim",
    dependencies = "neovim/nvim-lspconfig",
    event = "VeryLazy",
    opts = {
        -- your options here
        notifications = true,
        excluded_lsp_clients = { "jdtls" },
    },
}
```
but I always get the warning below:

>    Warn  11:37:35 notify.warn LazyVim `null-ls` is no longer included by default in **LazyVim**.
Please install the `lsp.none-ls` extra if you still want to use it.

When I disabled the `garbarge-day` plugin, the warning disappears, so I am wondering maybe this plugin triggers the `null-ls` checking? However, I checked the source code, I didn't find anything wrong.

**Comment by Zeioth** [comment]
The solution is to have:
```lua
excluded_lsp_clients = { "jdtls", "null-ls" },`
```
Because iIf `null-ls` is added to the `excluded_lsp_clients` list, garbage.nvim won't try to start it, and you won't get that warning (which is specific to your distro).

Also make sure you are using the latest version of `garbage-day.nvim`.

**Comment by neuromaancer** [comment]
oh, it works! thanks!
