### ISSUE TITLE
Handle `lspconfig.autostart`

### ISSUE THREAD

**Issue by qRoC** [Zeioth/garbage-day.nvim#7]
1. Add `autostart` to lsp:

```lua
lspconfig.*.setup {
    autostart = false,
}
```

2. Wait grace period
3. Go to nvim

Expected: all not enabled (before step 2) clients stay not enabled
Actual: Not enabled clients (by `autostart=false`) started

**Comment by Zeioth** [comment]
The only thing we do when nvim recover the focus is:

```lua
:LspStart
```
So this is config problem on your config. You can check the code [here](https://github.com/Zeioth/garbage-day.nvim/blob/035d83793199a5c7a801651098aa5119ef3227ab/lua/garbage-day/utils.lua#L44)

**Comment by qRoC** [comment]
> So this is a config problem on your side. You can check the code [here](https://github.com/Zeioth/garbage-day.nvim/blob/035d83793199a5c7a801651098aa5119ef3227ab/lua/garbage-day/utils.lua#L44).

`LspStart` start servers with `autostart = false`, so is not problem with my config.
