### ISSUE TITLE
Plugin.config is deprecated warning 

### ISSUE THREAD

**Issue by andrewcrook** [Zeioth/garbage-day.nvim#8]
Output from :checkhealth 

> WARNING {garbage-day.nvim}: setting a table to `Plugin.config` is deprecated. Please use `Plugin.opts` instead

**Comment by Zeioth** [comment]
The command is `:checkhealth` not :checkhelth

Also, this plugin doesn't support that command because there is nothing to check. It doesn't require any system dependency.

**Comment by Zeioth** [comment]
Could you post

**Comment by Zeioth** [comment]
Could you post a screenshot? This plugin don't implement checkhealth because there is really nothing to check. It has no system dependencies.

**Comment by andrewcrook** [comment]
@Zeioth  Apologies it's my fault it was a misconfiguration loading the plugin with Lazy I just couldn't see it at the time.
